#!/bin/sh
samtools reheader mapped/Undetermined_S0_L001-1.sorted.bam > mapped/Undetermined_S0_L001-1.sorted.noheader.bam
samtools reheader mapped/Undetermined_S0_L002-2.sorted.bam > mapped/Undetermined_S0_L002-2.sorted.noheader.bam
