#!/bin/sh
samtools view -HS mapped/Undetermined_S0_L001-1.sorted.sam | sort | uniq -c > mapped/Undetermined_S0_L001-1.sorted.uniq.sam
samtools view -HS mapped/Undetermined_S0_L002-2.sorted.sam | sort | uniq -c > mapped/Undetermined_S0_L002-2.sorted.uniq.sam
