#!/bin/sh
picard ValidateSamFile MODE=SUMMARY INPUT=mapped/Undetermined_S0_L001-1.sorted.bam OUTPUT=Undetermined_S0_L001-1.sorted.valid.bam
picard ValidateSamFile MODE=SUMMARY INPUT=mapped/Undetermined_S0_L002-2.sorted.bam OUTPUT=Undetermined_S0_L002-2.sorted.valid.bam
